name: CI

on: [push]

env:
  CI: true

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test

    steps:
      - uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v5
        with:
          version: latest

      - uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: pnpm

      - name: Build
        run: |
          pnpm install
          pnpm build

      - name: Unit tests
        run: pnpm test
